% Image Processing Toolbox AutoGenerated Script

%Initializations
diary(strcat('..\logs\Log_', datestr(now, 'yyyy-mm-dd_HH.MM.SS'), '.txt'));
	
%% ------------------------  EXTRACTION FOR FEATURE GROUP NR 1
%% Input arguments
directory='D:\banknoty\banknoty\images\classic\';
filter='*.tif';
inputHolder=DirInput(directory,filter);

%% Preprocessing stage
preProcessing=Preprocessing(inputHolder);
preProcessing.verboseMode(1);
numberOfPixels=4;
preProcessing.run(Crop(numberOfPixels));

%% Segmentation stage
segmentation=Segmentation(inputHolder);
segmentation.verboseMode(1);
windowSize=20;
at_threshold=0.01;
useMedian=0;
segmentation.run(SegAT(windowSize,at_threshold,useMedian));

%% Features Extraction stage
featuresExtraction=FeaturesExtraction(inputHolder);
featuresExtraction.verboseMode(1);
classificationGroup='banknoty';
features1=featuresExtraction.run(ExtractFeatures(classificationGroup));

% Collect all features
features=[features1; ];

%% ------------------------ STARTING SELECTION AND CLASSIFICATION
%y={'0', '10'; '200'; '20'; '50'; '100'; 'NIEZIDENTYFIKOWANY'};
Classification(features, 'full', '')
%% ------------------------END OF CLASSIFICATION PROCESS
diary off;