% Image Processing Toolbox AutoGenerated Script

%Initializations
diary(strcat('..\logs\Log_', datestr(now, 'yyyy-mm-dd_HH.MM.SS'), '.txt'));
	
%% Input arguments
directory='D:\impro_1.2.1\impro_1.2.1\workspace\CarsLogotypesRecognition\images\';
filter='*.png';
inputHolder=DirInput(directory,filter);

%% Preprocessing stage
preProcessing=Preprocessing(inputHolder);
preProcessing.verboseMode(1);
numberOfPixels=4;
preProcessing.run(Crop(numberOfPixels));

%% Segmentation stage
segmentation=Segmentation(inputHolder);
segmentation.verboseMode(1);
windowSize=20;
at_threshold=0.01;
useMedian=0;
segmentation.run(SegAT(windowSize,at_threshold,useMedian));

%% Features Extraction stage
featuresExtraction=FeaturesExtraction(inputHolder);
featuresExtraction.verboseMode(1);
classificationGroup='notUsed';
features=featuresExtraction.run(ExtractFeatures(classificationGroup));

%% ------------------------END OF CLASSIFICATION PROCESS
diary off;